package com.xvox.music.features.settings

data class SettingsState(
    val lyrics: com.xvox.music.data.preferences.LyricsSettings = com.xvox.music.data.preferences.LyricsSettings(),
    val theme: String = "System",
    val accentColor: String = "Red",
    val backgroundName: String = "Default",
    /** Custom photo behind the Home header; null keeps the theme surface. */
    val headerImageUri: String? = null,
    val backgroundImageUri: String? = null,
    val cardTransparency: Float = 0f,
    val fontSizeScale: Float = 1.0f,
    val fourRowsGrid: Boolean = true,
    val homeLayoutStyle: String = "mosaic1",
    val homeScrollDirection: String = "horizontal",
    val homeHorizontalRows: Int = 4,
    val hideRecentlyPlayed: Boolean = false,
    val recentsPlacement: String = "bottom",
    val eqHeadroomDb: Float = 0f,
    val surroundDepth: Float = 0.65f,
    val splitShowPill: Boolean = true,
    val splitHideCollection: Boolean = false,
    val playlistStyle: String = "long",
    val playlistLongHeight: Int = 0,
    /** Playlist cards on Home: full-width horizontally scrolling cards, or stacked vertically. */
    val playlistCardOrientation: String = "vertical",
    /** Appearance › "Hide preview" — the Settings top preview pane can be turned off. */
    val previewHidden: Boolean = false,
    /** Last Settings choice the user had open; restored on the next visit. */
    val lastSettingsTab: String = "Appearance",
    /** Per-size widget settings ("3x1" -> customization) so each widget size keeps its own. */
    val widgetSizes: Map<String, com.xvox.music.widget.WidgetCustomization> = emptyMap(),
    val homeMerge: Boolean = false,
    val homeSectionOrder: List<String> = com.xvox.music.features.home.HomeSections.defaultOrder,
    val homeHiddenSections: Set<String> = emptySet(),
    val crossfadeSmart: Boolean = true,
    val crossfadeClashControl: Float = .7f,
    val crossfadeBeatSync: Boolean = true,
    val widgetCustomization: com.xvox.music.widget.WidgetCustomization = com.xvox.music.widget.WidgetCustomization(),
    val widgetPaddingX: Int = 10,
    val widgetPaddingY: Int = 8,
    val sortOrder: String = "A-Z",
    val ignoreBelowSec: Int = 0,
    val ignoreBelowKb: Int = 0,
    val ignoredFolders: Set<String> = emptySet(),
    val crossfade: Boolean = false,
    val crossfadeDuration: Int = 3,
    val pauseOnHeadphoneDisconnect: Boolean = true,
    val playOnHeadsetConnect: Boolean = false,
    val btDisconnectAction: String = "pause",
    val btConnectAction: String = "none",
    val equalizerEnabled: Boolean = false,
    val eqPreset: String = "Flat",
    val eqBandCount: Int = 5,
    val noiseReduction: Float = 0f,
    val softenHighs: Float = 0f,
    val eqBands: List<Int> = listOf(0, 0, 0, 0, 0),
    val balance: Float = 0f,
    val stereoWidening: Boolean = false,
    val surroundPanSpeed: Int = 6,
    val surroundWidth: Float = 0.78f,
    val surroundPosition: Float = 0f,
    val roomAmount: Float = 0.5f,
    val reverbAmount: Float = 0f,
    val hrtf: Float = 0.6f,
    val centerPreservation: Float = 0f,
    val appVolume: Float = 1.0f,
    val volumeLimit: Float = 1.0f,
    val playbackSpeed: Float = 1.0f,
    val playbackPitch: Float = 1.0f,
    val widgetTransparency: Float = 0.25f,
    val widgetTheme: String = "Dark",
    val widgetCustomColor: String = "#000000",
    val widgetShowLogo: Boolean = true,
    val widgetCornerRadius: Int = 16,
    val chromeStyle: com.xvox.music.core.ui.chrome.XvoxChromeStyle = com.xvox.music.core.ui.chrome.XvoxChromeStyle(),
    val backgroundBrightness: Float = 0.8f,
    val audioOutputRoute: String = "auto",
    val profileLines: List<String> = emptyList(),
    val remindersEnabled: Boolean = false
)
