package com.xvox.music.features.settings

data class SettingsState(
    val theme: String = "System",
    val accentColor: String = "Default",
    val liveBlur: Boolean = true,
    val fontSizeScale: Float = 1.0f,
    val hapticFeedback: Boolean = true,
    val hapticStrength: String = "Medium",
    val gaplessPlayback: Boolean = true,
    val crossfade: Boolean = false,
    val crossfadeDuration: Int = 3,
    val fadeIn: Boolean = false,
    val fadeOut: Boolean = false,
    val replayGain: Boolean = false,
    val loudnessNormalization: Boolean = false,
    val skipSilence: Boolean = false,
    val audioFocus: Boolean = true,
    val pauseOnHeadphoneDisconnect: Boolean = true,
    val playOnHeadsetConnect: Boolean = false,
    val clearQueueAfterPlayback: Boolean = false,
    val rememberQueue: Boolean = true,
    val equalizerEnabled: Boolean = false,
    val eqPreset: String = "Flat",
    val eqBands: List<Int> = listOf(0, 0, 0, 0, 0),
    val bassBoost: Boolean = false,
    val bassBoostStrength: Int = 0,
    val virtualizerEnabled: Boolean = false,
    val virtualizerStrength: Int = 0,
    val loudnessEnhancer: Boolean = false,
    val loudnessGainMb: Int = 0,
    val balance: Float = 0f,
    val appVolume: Float = 1.0f,
    val rememberVolume: Boolean = true,
    val volumeLimit: Float = 1.0f,
    val mediaNotification: Boolean = true,
    val widgetTransparency: Float = 0.25f,
    val widgetTheme: String = "Dynamic",
    val widgetCustomColor: String = "#171717",
    val widgetShowLogo: Boolean = true,
    val widgetCornerRadius: Int = 24
)
